# postgreSQLを使うときのドライバーの定義
spring.datasource.driver-class-name=org.postgresql.Driver 
# データベースの接続先「jdbc:postgresql://(接続先):(ポート番号)/(データベース名)」
spring.datasource.url=jdbc:postgresql://localhost:5432/Fujichaku
# データベースへログインする時のユーザー名
spring.datasource.username=postgres
# データベースへログインする時のパスワード
spring.datasource.password=postgrestest
# SQLのカラム名がスネークケース、Javaがキャメルケースのときの自動変換
mybatis.configuration.map-underscore-to-camel-case=true