# postgreSQLを使うときのドライバーの定義
spring.datasource.driver-class-name=org.postgresql.Driver
# データベースへの接続URLを設定
spring.datasource.url=jdbc:postgresql://localhost:5432/Fujichaku
# データベース接続のためのユーザー名を設定
spring.datasource.username=postgres
# データベース接続のためのパスワードを設定
spring.datasource.password=postgrestest
# SQLのカラム名がスネークケース、Javaがキャメルケースのときの自動変換
mybatis.configuration.map-underscore-to-camel-case=true